#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

# use dependencies defined in metadata.json
#metadata

# use dependencies defined in Modulefile
# modulefile

# A module from the Puppet Forge
# mod 'puppetlabs-stdlib'

mod 'saz-motd' #shell welcome message
#mod 'jfryman-nginx' #install Nginx
mod 'moyo-nvm', :path => './custom-modules/nvm' #install Nvm
#mod 'artberri-nvm' #install Nvm
mod 'moyo-build_essential_install', :path => './custom-modules/build_essential_install'
mod 'moyo-npm_install', :path => './custom-modules/npm_install'
mod 'moyo-nginx', :path => './custom-modules/nginx'
mod 'puppetlabs-mongodb' #install MongoDb
#mod 'puppetlabs-git' #install Git
mod 'puppetlabs-vcsrepo' #manage git


# A module from git
# mod 'puppetlabs-ntp',
#   :git => 'git://github.com/puppetlabs/puppetlabs-ntp.git'

# A module from a git branch/tag
# mod 'puppetlabs-apt',
#   :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
#   :ref => '1.4.x'

# A module from Github pre-packaged tarball
# mod 'puppetlabs-apache', '0.6.0', :github_tarball => 'puppetlabs/puppetlabs-apache'
